### ISSUE TITLE
image verson is incorrect

### ISSUE THREAD

**Issue by bittu664** [ixoncloud/cert-manager-webhook-cloudns#12]
hello team, actually your image version is wrong , see currently  you mentioned this image in your make file:- 
![Screenshot 2023-04-25 at 4 14 38 PM](https://user-images.githubusercontent.com/28609215/234253828-7857b62b-13c1-4e81-9c06-a58bc34d4899.png)

But when i pull this image it shows 
![Screenshot 2023-04-25 at 4 15 23 PM](https://user-images.githubusercontent.com/28609215/234253973-c281d9f1-b60e-43d4-830d-c76e0005f63a.png)

so i  checked in the dockerhub and this is i found :- 
![Screenshot 2023-04-25 at 4 16 04 PM](https://user-images.githubusercontent.com/28609215/234254153-3d909bab-7a81-480e-815e-c495fa8618bf.png)

so i think the correct one is this :-  mschirrmeister/cert-manager-webhook-cloudns:v1.0.4

**Comment by raqbit** [comment]
Hi there, this is an issue in the fork by @mschirrmeister, not of the original project. Please open an issue in https://github.com/mschirrmeister/cert-manager-webhook-cloudns instead.
