### ISSUE TITLE
is this compatible with cert-manager 0.13?

### ISSUE THREAD

**Issue by yctn** [ixoncloud/cert-manager-webhook-cloudns#4]
https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/

it seems that certmanager.k8s.io is not valid anymore. they changed it into 
cert-manager.io

so it seems this cannot be used with newer versions of cert-manager.
would it be possible fix this?

i tryed to fix the rendered-manifest.yaml myself but that wasnt a succes.

**Comment by yctn** [comment]
bump

**Comment by Raqbit** [comment]
@yctn It appears this is mainly a deprecation, and this repo should still work, but I'll rebase this repo on the latest helm template.

**Comment by Raqbit** [comment]
Closing as cert-manager-webhook-cloudns should now be compatible with cert-manager versions from v0.13 all the way to 1.5.x and probably 1.6.x

**Comment by RonNabuurs** [comment]
I'm running the latest https://hub.docker.com/r/ixoncloud/cert-manager-webhook-cloudns together with cert-manager `1.5.4` and everything is working flawlessly.
